// @generated by scripts/generate-engine-contracts.py; do not edit.
import capabilityMatrix from "./engine-capability-matrix.generated.json";
import transportParity from "./engine-transport-parity.generated.json";

export const ENGINE_CAPABILITY_MATRIX = capabilityMatrix;
export const ENGINE_TRANSPORT_PARITY = transportParity;
export const ENGINE_CAPABILITY_AUTHORITY_ID = capabilityMatrix.authority_id;
export const ENGINE_COUNT = capabilityMatrix.engine_count;
export type EngineCapabilityStatus = keyof typeof capabilityMatrix.status_vocabulary;
