// @generated by scripts/generate-engine-authorities.py; do not edit.
import assemblyAuthority from "./assembly-authority.generated.json";
import consensusAuthority from "./consensus-authority.generated.json";
import discriminatingAuthority from "./discriminating-authority.generated.json";
import inverseAuthority from "./inverse-authority.generated.json";
import mutagenesisAuthority from "./mutagenesis-authority.generated.json";
import nestedAuthority from "./nested-authority.generated.json";
import probeAuthority from "./probe-authority.generated.json";
import raceAuthority from "./race-authority.generated.json";
import sequencingAuthority from "./sequencing-authority.generated.json";
import tilingAuthority from "./tiling-authority.generated.json";
import flankingAuthority from "./flanking-protocol-authority.generated.json";
import lampAuthority from "./lamp-protocol-authority.generated.json";

export const ASSEMBLY_AUTHORITY = assemblyAuthority;
export const ASSEMBLY_CAPABILITIES = ["standard-overlap", "three-prime-mismatch-removal", "ssdna-bridge", "restriction-generated-vector"] as const;
export const ASSEMBLY_FRAGMENT_KINDS = ["pcr-amplified", "restriction-digest", "synthetic-dsdna", "ssdna-oligo", "annealed-oligos", "existing-linear", "literal"] as const;
export const ASSEMBLY_METHODS = ["gibson", "nebuilder", "in-fusion-reference", "iva-reference"] as const;
export const ASSEMBLY_PROTOCOLS = ["not-selected", "neb-e5510", "neb-nebuilder-e2621", "neb-nebuilder-e5520", "neb-nebuilder-e2623"] as const;
export const ASSEMBLY_TOPOLOGIES = ["linear", "circular"] as const;

export const CONSENSUS_AUTHORITY = consensusAuthority;
export const CONSENSUS_ALIGNMENT_BACKENDS = ["mafft-7.526", "prealigned-reviewed", "muscle-5.3-audit"] as const;
export const CONSENSUS_CAPABILITY_STATUSES = ["executable", "executable-if-installed", "diagnostic-only", "reference-only", "unresolved", "historical"] as const;
export const CONSENSUS_CHARACTERIZATION_TOOLS = ["degeprime-reference", "degenprime-2024-reference", "varvamp-2025-reference", "decipher-designprimers-reference", "consensusprime-reference"] as const;
export const CONSENSUS_CONSENSUS_POLICIES = ["strict-all-members", "coverage-threshold", "majority", "weighted", "stratified"] as const;
export const CONSENSUS_COVERAGE_MODES = ["observed-panel", "weighted-panel", "stratified-panel", "target-vs-nontarget"] as const;
export const CONSENSUS_FORMULATION_MODES = ["mixed-base-synthesis", "defined-oligo-pool", "discrete-subprimer-mixture", "user-defined-formulation"] as const;

export const DISCRIMINATING_AUTHORITY = discriminatingAuthority;
export const DISCRIMINATING_GEL_READOUTS = ["agarose", "polyacrylamide", "capillary", "other-validated"] as const;
export const DISCRIMINATING_GEOMETRIES = ["arms-two-tube", "tetra", "kasp"] as const;
export const DISCRIMINATING_KASP_CALL_STATES = ["AA", "AB", "BB", "no-template", "no-call", "weak", "ambiguous-cluster", "failed-assay"] as const;
export const DISCRIMINATING_POLYMERASE_CLASSES = ["taq-no-proofreading", "unknown-no-proofreading", "proofreading-prohibited"] as const;
export const DISCRIMINATING_PROTOCOLS = ["not-selected", "arms-experimental-taq", "tetra-collins-day-2001-reference", "lgc-kasp-tf-v5", "lgc-standard"] as const;
export const DISCRIMINATING_KASP_PROTOCOLS = ["not-selected", "lgc-kasp-tf-v5", "lgc-standard"] as const;
export const DISCRIMINATING_VARIANT_CLASSES = ["snv", "mnv", "insertion", "deletion", "complex-replacement", "presence-absence"] as const;
export const DISCRIMINATING_MISMATCH_MODEL_ID = "pcrstudio-gen1-taq-terminal-mismatch-evidence-2026" as const;

export const INVERSE_AUTHORITY = inverseAuthority;
export const INVERSE_BRANCHES = ["restriction-self-ligation", "supplied-circular-template", "one-sided-internal-cut-reference"] as const;
export const INVERSE_ENZYME_DECISION_INPUTS = ["known-anchor-cut-count", "methylation-compatibility", "end-type", "heat-inactivation", "star-activity", "buffer-compatibility"] as const;
export const INVERSE_RESULT_STATUS = ["exact", "bounded", "unresolved"] as const;

export const MUTAGENESIS_AUTHORITY = mutagenesisAuthority;
export const MUTAGENESIS_CODON_POLICIES = ["minimum-nucleotide-changes", "user-selected-codon", "host-codon-usage"] as const;
export const MUTAGENESIS_EDIT_KINDS = ["substitute", "insert", "delete"] as const;
export const MUTAGENESIS_LIBRARY_MODES = ["none", "NNK", "NNS", "custom-codon-set"] as const;
export const MUTAGENESIS_PROTOCOLS = ["neb-q5-e0554", "agilent-quikchange-lightning-210518", "agilent-quikchange-lightning-multi-210513-210516", "neb-nebuilder-multisite"] as const;
export const MUTAGENESIS_TOPOLOGY_FAMILIES = ["q5-back-to-back", "quikchange-complementary", "quikchange-lightning-multi", "nebuilder-multisite"] as const;

export const NESTED_AUTHORITY = nestedAuthority;
export const NESTED_CARRYOVER_STRATEGIES = ["not-selected", "dutp-ung-strategy-only", "named-protocol"] as const;
export const NESTED_CLEANUP_PROTOCOLS = ["not-selected", "neb-msz-exonuclease-i", "neb-thermolabile-exonuclease-i"] as const;
export const NESTED_TOPOLOGIES = ["fully-nested-two-tube", "semi-nested-forward-two-tube", "semi-nested-reverse-two-tube", "one-tube-reference-only"] as const;
export const NESTED_TRANSFER_MODES = ["direct-transfer", "diluted-transfer", "msz-exonuclease-i", "thermolabile-exonuclease-i", "purified-product", "custom-sop"] as const;

export const PROBE_AUTHORITY = probeAuthority;
export const PROBE_CHEMISTRIES = ["conventional-hydrolysis", "double-quenched-hydrolysis", "mgb-nfq"] as const;
export const PROBE_EVIDENCE_STANDARD = ["MIQE-2.0"] as const;
export const PROBE_PROBE_PROTOCOLS = ["thermofisher-taqman-conventional", "idt-primetime-conventional", "taqman-mgb-reference"] as const;
export const PROBE_QUENCHERS = ["TAMRA", "QSY", "QSY2", "Iowa Black FQ", "ZEN+Iowa Black FQ", "NFQ-MGB"] as const;
export const PROBE_REPORTERS = ["FAM", "VIC", "HEX", "ABY", "JUN", "Cy5", "TET", "NED"] as const;

export const RACE_AUTHORITY = raceAuthority;
export const RACE_CHEMISTRIES = ["generacer-kit-25-0355-vl", "firstchoice-rlm-race", "smarter-race-source-limited", "custom", "smarter-race-current"] as const;
export const RACE_DIRECTIONS = ["5prime", "3prime"] as const;
export const RACE_ROUNDS = ["primary", "nested"] as const;
export const RACE_SUBSTRATES = ["total-rna", "mrna", "cdna"] as const;

export const SEQUENCING_AUTHORITY = sequencingAuthority;
export const SEQUENCING_CHEMISTRY_PROTOCOLS = ["not-selected", "bigdye-v3-1"] as const;
export const SEQUENCING_DESIGN_PROFILES = ["generic-cycle-sequencing", "azenta-genewiz", "eurofins", "cornell"] as const;
export const SEQUENCING_UNIVERSAL_PRIMERS = ["T7", "T7-Term", "T3", "SP6", "BGHR", "M13F", "M13R", "M13-40FOR", "M13-48REV", "CMV-Forward"] as const;

export const TILING_AUTHORITY = tilingAuthority;
export const TILING_BACKENDS = ["primalscheme3-3.3.0", "olivar-1.3.3", "olivar-publication-repro-1.1.5", "internal-development"] as const;
export const TILING_OPERATIONS = ["scheme-create", "panel-create", "repair-mode", "scheme-replace"] as const;
export const TILING_SCHEME_FORMATS = ["artic-primer-bed-v3", "pcrstudio-tiling-v1"] as const;
export const TILING_TARGET_MODES = ["single-target", "multi-target", "segmented-genome"] as const;

export const FLANKING_AUTHORITY = flankingAuthority;

export const LAMP_AUTHORITY = lampAuthority;
