// @generated by scripts/generate-flanking-protocol-authority.py; do not edit.
export const FLANKING_PROTOCOL_GROUPS = {
  "colony_host_classes": [
    "bacterial",
    "filamentous-fungus",
    "microalgae",
    "other",
    "yeast"
  ],
  "colony_preparations": [
    "buffer-lysate",
    "direct-transfer",
    "host-specific-lysis",
    "liquid-culture",
    "other",
    "water-lysate"
  ],
  "colony_protocols": [
    "custom-sop",
    "neb-onetaq-m0482-colony",
    "neb-onetaq-hotstart-m0488-colony",
    "neb-insert-screening-e1202",
    "pcrbio-hs-taq-pb10-22-colony",
    "neb-onetaq-m0689-colony"
  ],
  "digital": [
    "not-selected",
    "bio-rad-qx200-evagreen",
    "bio-rad-qx700-naica-evagreen",
    "bio-rad-qx700-evagreen-supermix",
    "qiagen-qiacuity-eg",
    "qiagen-qiacuity-onestep-advanced-eg"
  ],
  "digital_consumable_ids": [
    "not-specified",
    "qx700-rdg16",
    "naica-sapphire-chip",
    "qx-continuum-96well",
    "qiacuity-8.5k",
    "qiacuity-26k",
    "absolute-q-map16",
    "roche-universal",
    "roche-high-sensitivity",
    "roche-high-resolution",
    "other-validated"
  ],
  "digital_fragmentation_states": [
    "not-assessed",
    "not-required",
    "performed",
    "planned"
  ],
  "digital_partition_formats": [
    "chamber",
    "chip",
    "droplet",
    "other"
  ],
  "digital_platform_ids": [
    "bio-rad-naica",
    "bio-rad-nio",
    "bio-rad-qx-continuum",
    "bio-rad-qx-one",
    "bio-rad-qx200",
    "bio-rad-qx600",
    "bio-rad-qx700",
    "other-validated",
    "qiagen-qiacuity",
    "roche-digital-lightcycler",
    "thermo-absolute-q"
  ],
  "long_range": [
    "not-selected",
    "thermo-long-pcr-k018x",
    "neb-longamp-taq-m0323",
    "takara-primestar-gxl-r050a-standard",
    "qiagen-ultrarun-longrange-206442-206444",
    "neb-q5-xt-m2499",
    "promega-gotaq-long-m4021",
    "thermo-platinum-superfi-ii-longrange",
    "toyobo-kod-long-kml101"
  ],
  "qpcr_instrument_profiles": [
    "unresolved",
    "high-rox",
    "low-rox",
    "rox-compatible",
    "no-rox",
    "capillary"
  ],
  "qpcr_sybr": [
    "not-selected",
    "bio-rad-itaq-sybr",
    "neb-luna-universal-m3003",
    "neb-luna-one-step-rt-qpcr-e3005",
    "thermo-powerup-sybr-a2574x",
    "promega-gotaq-qpcr-a600x",
    "promega-gotaq-one-step-rt-qpcr-a6020",
    "thermo-powertrack-sybr-a46xxx",
    "qiagen-quantinova-sybr-208052",
    "bio-rad-ssoadvanced-sybr-172527x",
    "solis-hot-firepol-evagreen-rox",
    "solis-hot-firepol-evagreen-norox",
    "solis-hot-firepol-evagreen-capillary",
    "vazyme-q713-suprealq-ultra-hunter-sybr"
  ],
  "restriction_dephosphorylation_protocols": [
    "none",
    "neb-quick-cip-m0525"
  ],
  "restriction_digest_protocols": [
    "neb-cutsmart-standard",
    "neb-cutsmart-timesaver",
    "thermo-fastdigest-universal"
  ],
  "restriction_ligation_protocols": [
    "neb-t4-dna-ligase-m0202",
    "neb-quick-ligation-m2200"
  ],
  "rpa": [
    "not-selected",
    "twistamp-basic",
    "twistamp-liquid-basic",
    "thermo-lyo-ready-rpa",
    "gbiosciences-rpa-786-2155",
    "twistamp-exo",
    "twistamp-nfo",
    "twistamp-fpg",
    "siba-reference"
  ],
  "rpa_executable": [
    "twistamp-basic",
    "twistamp-liquid-basic",
    "thermo-lyo-ready-rpa",
    "gbiosciences-rpa-786-2155"
  ],
  "standard_pcr": [
    "not-selected",
    "neb-taq-m0273",
    "neb-q5-hot-start-m0493",
    "neb-q5u-hot-start-m0515",
    "thermo-dreamtaq-hot-start-ep170x",
    "thermo-phusion-plus",
    "promega-gotaq-m300",
    "thermo-platinum-superfi-ii",
    "neb-onetaq-hot-start-m0484",
    "neb-onetaq-hot-start-gc-m0485",
    "neb-onetaq-hot-start-quickload-m0488",
    "neb-onetaq-hot-start-quickload-gc-m0489",
    "pcrbio-hs-taq-mix-pb10-22",
    "qiagen-alltaq-master-mix-203144",
    "thermo-platinum-ii-taq-hot-start",
    "toyobo-kod-one-kmm101",
    "neb-multiplex-pcr-m0284"
  ]
} as const;

export const DIGITAL_CONSUMABLE_PLATFORMS = {
  "absolute-q-map16": [
    "thermo-absolute-q"
  ],
  "naica-sapphire-chip": [
    "bio-rad-naica"
  ],
  "not-specified": [
    "bio-rad-naica",
    "bio-rad-nio",
    "bio-rad-qx200",
    "bio-rad-qx600",
    "bio-rad-qx-one",
    "bio-rad-qx700",
    "bio-rad-qx-continuum",
    "qiagen-qiacuity",
    "thermo-absolute-q",
    "roche-digital-lightcycler",
    "other-validated"
  ],
  "other-validated": [
    "other-validated"
  ],
  "qiacuity-26k": [
    "qiagen-qiacuity"
  ],
  "qiacuity-8.5k": [
    "qiagen-qiacuity"
  ],
  "qx-continuum-96well": [
    "bio-rad-qx-continuum"
  ],
  "qx700-rdg16": [
    "bio-rad-qx700",
    "bio-rad-nio",
    "bio-rad-naica"
  ],
  "roche-high-resolution": [
    "roche-digital-lightcycler"
  ],
  "roche-high-sensitivity": [
    "roche-digital-lightcycler"
  ],
  "roche-universal": [
    "roche-digital-lightcycler"
  ]
} as const;

export const DIGITAL_PROTOCOL_PLATFORMS = {
  "bio-rad-qx200-evagreen": [
    "bio-rad-qx200",
    "bio-rad-qx600",
    "bio-rad-qx-one"
  ],
  "bio-rad-qx700-evagreen-supermix": [
    "bio-rad-qx700"
  ],
  "bio-rad-qx700-naica-evagreen": [
    "bio-rad-qx700",
    "bio-rad-nio",
    "bio-rad-naica"
  ],
  "qiagen-qiacuity-eg": [
    "qiagen-qiacuity"
  ],
  "qiagen-qiacuity-onestep-advanced-eg": [
    "qiagen-qiacuity"
  ]
} as const;

export const DIGITAL_PLATFORM_ROUTES = {
  "bio-rad-naica": "dye-flanking",
  "bio-rad-nio": "dye-flanking",
  "bio-rad-qx-continuum": "pair-probe",
  "bio-rad-qx-one": "dye-flanking",
  "bio-rad-qx200": "dye-flanking",
  "bio-rad-qx600": "dye-flanking",
  "bio-rad-qx700": "dye-flanking",
  "other-validated": "custom-validated",
  "qiagen-qiacuity": "dye-flanking",
  "roche-digital-lightcycler": "pair-probe",
  "thermo-absolute-q": "pair-probe"
} as const;

export const DIGITAL_PLATFORM_LABELS = {
  "bio-rad-naica": "Bio-Rad naica",
  "bio-rad-nio": "Bio-Rad Nio",
  "bio-rad-qx-continuum": "Bio-Rad QX Continuum",
  "bio-rad-qx-one": "Bio-Rad QX ONE",
  "bio-rad-qx200": "Bio-Rad QX200",
  "bio-rad-qx600": "Bio-Rad QX600",
  "bio-rad-qx700": "Bio-Rad QX700",
  "qiagen-qiacuity": "QIAGEN QIAcuity",
  "roche-digital-lightcycler": "Roche Digital LightCycler",
  "thermo-absolute-q": "Thermo Fisher QuantStudio Absolute Q"
} as const;

export const DIGITAL_PLATFORM_NAME_ALIASES = {
  "bio-rad-naica": [
    "bio-rad naica",
    "naica",
    "naica system"
  ],
  "bio-rad-nio": [
    "bio-rad nio",
    "nio",
    "nio digital pcr system"
  ],
  "bio-rad-qx-continuum": [
    "bio-rad qx continuum",
    "bio-rad qx continuum ddpcr"
  ],
  "bio-rad-qx-one": [
    "bio-rad qx one",
    "bio-rad qx one ddpcr"
  ],
  "bio-rad-qx200": [
    "bio-rad qx200",
    "bio-rad qx200 ddpcr"
  ],
  "bio-rad-qx600": [
    "bio-rad qx600",
    "bio-rad qx600 ddpcr"
  ],
  "bio-rad-qx700": [
    "bio-rad qx700",
    "bio-rad qx700 ddpcr",
    "bio-rad qx700 droplet digital pcr system"
  ],
  "qiagen-qiacuity": [
    "qiagen qiacuity",
    "qiacuity",
    "qiagen qiacuity digital pcr system"
  ],
  "roche-digital-lightcycler": [
    "roche digital lightcycler",
    "digital lightcycler",
    "roche digital lightcycler system"
  ],
  "thermo-absolute-q": [
    "thermo fisher quantstudio absolute q",
    "quantstudio absolute q",
    "absolute q"
  ]
} as const;

export type QpcrInstrumentProfile = typeof FLANKING_PROTOCOL_GROUPS.qpcr_instrument_profiles[number];
export type DigitalConsumableId = typeof FLANKING_PROTOCOL_GROUPS.digital_consumable_ids[number];
export type DigitalPlatformId = typeof FLANKING_PROTOCOL_GROUPS.digital_platform_ids[number];
export type ColonyHostClass = typeof FLANKING_PROTOCOL_GROUPS.colony_host_classes[number];
export type ColonyPreparation = typeof FLANKING_PROTOCOL_GROUPS.colony_preparations[number];
