// @generated by scripts/generate-multiplex-capabilities.py; do not edit.
#[derive(Debug, Clone, Copy)]
/// Source-backed capability limits for one digital multiplex platform.
pub struct DigitalMultiplexPlatformAuthority {
    /// Human-readable platform family.
    pub family: &'static str,
    /// Number of independently detected channels.
    pub detection_channels: usize,
    /// Maximum target count supported by the reviewed authority.
    pub multiplex_target_bound: usize,
    /// Supported multiplex representation modes.
    pub modes: &'static [&'static str],
}

/// Resolve a platform identifier to its reviewed capability authority.
pub fn digital_multiplex_platform_authority(id: &str) -> Option<DigitalMultiplexPlatformAuthority> {
    match id {
        "bio-rad-qx-continuum" => Some(DigitalMultiplexPlatformAuthority { family: "QX Continuum", detection_channels: 4, multiplex_target_bound: 4, modes: &["channel"] }),
        "bio-rad-qx-one" => Some(DigitalMultiplexPlatformAuthority { family: "QX ONE", detection_channels: 4, multiplex_target_bound: 8, modes: &["channel", "amplitude", "probe-mix"] }),
        "bio-rad-qx200" => Some(DigitalMultiplexPlatformAuthority { family: "QX200", detection_channels: 2, multiplex_target_bound: 2, modes: &["channel"] }),
        "bio-rad-qx600" => Some(DigitalMultiplexPlatformAuthority { family: "QX600", detection_channels: 6, multiplex_target_bound: 12, modes: &["channel", "amplitude", "probe-mix"] }),
        "bio-rad-qx700" => Some(DigitalMultiplexPlatformAuthority { family: "QX700", detection_channels: 7, multiplex_target_bound: 7, modes: &["channel"] }),
        "qiacuity-eight" => Some(DigitalMultiplexPlatformAuthority { family: "QIAcuity", detection_channels: 8, multiplex_target_bound: 12, modes: &["channel", "amplitude", "hybrid"] }),
        "qiacuity-four" => Some(DigitalMultiplexPlatformAuthority { family: "QIAcuity", detection_channels: 8, multiplex_target_bound: 12, modes: &["channel", "amplitude", "hybrid"] }),
        "qiacuity-one-2plex" => Some(DigitalMultiplexPlatformAuthority { family: "QIAcuity", detection_channels: 2, multiplex_target_bound: 4, modes: &["channel", "amplitude"] }),
        "qiacuity-one-5plex" => Some(DigitalMultiplexPlatformAuthority { family: "QIAcuity", detection_channels: 8, multiplex_target_bound: 12, modes: &["channel", "amplitude", "hybrid"] }),
        "roche-digital-lightcycler" => Some(DigitalMultiplexPlatformAuthority { family: "Digital LightCycler", detection_channels: 6, multiplex_target_bound: 6, modes: &["channel"] }),
        "thermo-absolute-q" => Some(DigitalMultiplexPlatformAuthority { family: "QuantStudio Absolute Q", detection_channels: 5, multiplex_target_bound: 5, modes: &["channel"] }),
        _ => None,
    }
}
