// @generated by scripts/generate-lamp-protocol-authority.py; do not edit.
/// Closed vocabulary for the `protocols` authority group.
pub const LAMP_PROTOCOLS: &[&str] = &[
    "not-selected",
    "neb-e1700",
    "neb-e1708",
    "neb-l4401",
    "neb-m1708",
    "neb-m1800",
    "neb-m1804",
    "neb-m1712",
    "neb-m9204",
    "neb-m9205",
    "thermo-a5180x",
    "nippon-ne6041",
    "eiken-lmp204",
    "eiken-lmp207",
    "eiken-lmp247",
    "eiken-lmp244",
    "neb-m0275",
    "neb-m0537",
    "neb-m0538",
    "neb-m0374",
    "neb-m0402-m0439-rt",
    "thermo-a56656",
    "optigene-iso004",
    "optigene-iso004-rt",
    "optigene-iso004-lnl",
    "optigene-iso004-rt-vis",
    "optigene-dr004",
    "optigene-dr004-rt",
    "optigene-iso004-lyo",
    "optigene-iso004-rt-lyo",
    "meridian-mdx097",
    "meridian-mdx108",
    "meridian-mdx118",
    "meridian-mdx119",
    "meridian-mdx124",
    "meridian-mdx125",
    "meridian-mdx126",
    "meridian-mdx134",
    "meridian-mdx135",
    "meridian-mdx144",
    "meridian-mdx145",
    "meridian-mdx154",
    "meridian-mdx155",
    "takara-rr385",
    "optigene-iso001",
    "optigene-iso001-rt",
    "optigene-iso001-lnl",
    "optigene-dr001",
    "optigene-dr001-lnl",
    "optigene-iso001-lyo",
    "optigene-iso001-rt-lyo",
    "optigene-iso001tin",
    "jena-pcr387",
    "jena-pcr393",
    "jena-pcr398",
    "jena-pcr395",
    "jena-pcr540",
    "jena-pcr541",
    "nzy-md0696",
    "nzy-md0697",
    "nippon-dr0401",
    "nippon-dr0701",
    "nippon-heatact-fluorescence",
    "nippon-heatact-turbidity",
    "nippon-heatact-turbidity-visible",
    "yeasen-16729",
    "yeasen-16730",
    "vazyme-rp711",
    "agdia-lmx54700",
    "vazyme-rp712",
    "hyasen-hyb413",
    "hyasen-hyb414",
    "hyasen-hyb315",
];

/// Closed vocabulary for the `readouts` authority group.
pub const LAMP_READOUTS: &[&str] = &[
    "not-specified",
    "fluorescence",
    "colorimetric",
    "turbidity",
    "other-validated",
];

/// Closed vocabulary for the `readout_chemistries` authority group.
pub const LAMP_READOUT_CHEMISTRIES: &[&str] = &[
    "not-specified",
    "supplied-intercalating-dye",
    "syto9",
    "syto82",
    "tb-green",
    "nzy-speedy-lamp-dye",
    "eiken-fd-lmp221",
    "calcein",
    "hydroxynaphthol-blue",
    "eriochrome-black-t",
    "ph-colorimetric",
    "vendor-visual-color-change",
    "turbidity-pyrophosphate",
    "agarose-gel-endpoint",
    "other-validated",
];

/// Closed vocabulary for the `sample_matrices` authority group.
pub const LAMP_SAMPLE_MATRICES: &[&str] = &[
    "not-specified",
    "purified-nucleic-acid",
    "crude-unspecified",
    "saliva-sputum",
    "blood-plasma-serum",
    "stool",
    "urine",
    "koh-lysate",
    "other-validated",
];

/// Closed vocabulary for the `sample_preparations` authority group.
pub const LAMP_SAMPLE_PREPARATIONS: &[&str] = &[
    "not-specified",
    "purified",
    "extracted-crude",
    "direct-addition",
    "koh-lyse-and-lamp",
    "other-validated",
];

/// Closed vocabulary for the `formulations` authority group.
pub const LAMP_FORMULATIONS: &[&str] = &[
    "not-specified",
    "liquid",
    "lyophilized",
    "air-dryable",
    "dry-reagent",
    "assembled-enzyme",
    "lyophilizable",
];

/// Closed vocabulary for the `confirmation_modes` authority group.
pub const LAMP_CONFIRMATION_MODES: &[&str] = &[
    "not-specified",
    "none",
    "anneal-curve",
    "melt-denaturation-curve",
    "gel-ladder",
    "sequence-confirmation",
    "other-validated",
];

/// Closed vocabulary for the `detection_topologies` authority group.
pub const LAMP_DETECTION_TOPOLOGIES: &[&str] = &[
    "nonspecific-dsdna",
    "sequence-specific-probe",
    "multiplex-modified-primer-probe",
    "lateral-flow-modified-primer",
];

/// Closed vocabulary for the `design_intents` authority group.
pub const LAMP_DESIGN_INTENTS: &[&str] = &[
    "standard",
    "panel-conservation-aware",
    "fixed-primer-anchor",
    "mutation-anchored-specific",
];

/// Closed vocabulary for the `loop_policies` authority group.
pub const LAMP_LOOP_POLICIES: &[&str] = &[
    "prefer-six",
    "require-six",
    "core-four-only",
];

/// Closed vocabulary for the `design_stages` authority group.
pub const LAMP_DESIGN_STAGES: &[&str] = &[
    "integrated",
    "core-first",
    "add-loops",
];

/// Closed vocabulary for the `parameter_sets` authority group.
pub const PARAMETER_SETS: &[&str] = &[
    "normal",
    "at-rich",
    "gc-rich",
];

/// Closed vocabulary for the `geometry_profiles` authority group.
pub const LAMP_GEOMETRY_PROFILES: &[&str] = &[
    "primerexplorer-v5-compat",
    "pcrstudio-evidence-2026",
];

/// Closed vocabulary for the `inner_linkers` authority group.
pub const LAMP_INNER_LINKERS: &[&str] = &[
    "none",
    "tttt",
];

/// Closed vocabulary for the `instrument_profiles` authority group.
pub const LAMP_INSTRUMENT_PROFILES: &[&str] = &[
    "not-specified",
    "vazyme-slan96p",
    "vazyme-quantstudio3",
    "vazyme-quantstudio5",
    "vazyme-steponeplus",
    "vazyme-lightcycler96",
    "vazyme-cfx96-touch",
    "vazyme-quantgene9600",
    "vazyme-gentier96r",
    "agdia-amplifire",
    "other-qpcr",
    "other-validated",
];

/// Closed vocabulary for the `carryover_strategies` authority group.
pub const LAMP_CARRYOVER_STRATEGIES: &[&str] = &[
    "protocol-default",
    "reviewed-dutp-udg",
];

/// Closed vocabulary for the `reconstitution_options` authority group.
pub const LAMP_RECONSTITUTION_OPTIONS: &[&str] = &[
    "protocol-default",
    "2x",
    "4x",
];

/// Closed vocabulary for the `specificity_additives` authority group.
pub const LAMP_SPECIFICITY_ADDITIVES: &[&str] = &[
    "none",
    "tte-uvrd-reviewed",
];

/// Closed vocabulary for the `acceleration_additives` authority group.
pub const LAMP_ACCELERATION_ADDITIVES: &[&str] = &[
    "none",
    "guanidine-hcl-40mm",
];

/// Closed vocabulary for the `primer_kinetics_profiles` authority group.
pub const LAMP_PRIMER_KINETICS_PROFILES: &[&str] = &[
    "protocol-default",
    "optigene-standard",
    "optigene-high",
];

/// Closed vocabulary for the `preincubation_strategies` authority group.
pub const LAMP_PREINCUBATION_STRATEGIES: &[&str] = &[
    "protocol-default",
    "takara-ung-25c-10min",
];

/// Closed vocabulary for the `sample_buffer_types` authority group.
pub const LAMP_SAMPLE_BUFFER_TYPES: &[&str] = &[
    "none",
    "water",
    "te",
    "other-buffered",
    "chelating-other",
];

/// Closed vocabulary for the `mutation_anchors` authority group.
pub const LAMP_MUTATION_ANCHORS: &[&str] = &[
    "fip-3p-f2",
    "bip-3p-b2",
    "fip-5p-f1c",
    "bip-5p-b1c",
];

/// Closed vocabulary for the `fixed_primer_roles` authority group.
pub const LAMP_FIXED_PRIMER_ROLES: &[&str] = &[
    "F3",
    "B3",
    "FIP",
    "BIP",
    "LF",
    "LB",
];

/// Derived protocol vocabulary for the `LAMP_DNA_ONLY_PROTOCOLS` compatibility branch.
pub const LAMP_DNA_ONLY_PROTOCOLS: &[&str] = &[
    "eiken-lmp204",
    "eiken-lmp207",
    "hyasen-hyb315",
    "jena-pcr387",
    "jena-pcr393",
    "jena-pcr395",
    "jena-pcr398",
    "meridian-mdx097",
    "meridian-mdx118",
    "meridian-mdx119",
    "meridian-mdx124",
    "meridian-mdx126",
    "meridian-mdx134",
    "meridian-mdx144",
    "meridian-mdx154",
    "neb-m0275",
    "neb-m0537",
    "neb-m0538",
    "nippon-dr0401",
    "nippon-heatact-fluorescence",
    "nippon-heatact-turbidity",
    "nippon-heatact-turbidity-visible",
    "nippon-ne6041",
    "nzy-md0696",
    "optigene-dr001",
    "optigene-dr001-lnl",
    "optigene-dr004",
    "optigene-iso001",
    "optigene-iso001-lnl",
    "optigene-iso001-lyo",
    "optigene-iso001tin",
    "optigene-iso004",
    "optigene-iso004-lnl",
    "optigene-iso004-lyo",
    "thermo-a56656",
];

/// Derived protocol vocabulary for the `LAMP_RNA_ONLY_PROTOCOLS` compatibility branch.
pub const LAMP_RNA_ONLY_PROTOCOLS: &[&str] = &[
    "eiken-lmp244",
    "jena-pcr540",
    "jena-pcr541",
    "nippon-dr0701",
];

/// Derived compatibility pairs for the `LAMP_DIRECT_SAMPLE_PAIRS` authority branch.
pub const LAMP_DIRECT_SAMPLE_PAIRS: &[(&str, &str)] = &[
    ("meridian-mdx124", "blood-plasma-serum"),
    ("meridian-mdx125", "blood-plasma-serum"),
    ("meridian-mdx126", "blood-plasma-serum"),
    ("meridian-mdx134", "saliva-sputum"),
    ("meridian-mdx135", "saliva-sputum"),
    ("meridian-mdx144", "stool"),
    ("meridian-mdx145", "stool"),
    ("meridian-mdx154", "urine"),
    ("meridian-mdx155", "urine"),
    ("optigene-dr001-lnl", "koh-lysate"),
    ("optigene-iso001-lnl", "koh-lysate"),
    ("optigene-iso004-lnl", "koh-lysate"),
];

/// Derived compatibility pairs for the `LAMP_PROTOCOL_FORMULATION_PAIRS` authority branch.
pub const LAMP_PROTOCOL_FORMULATION_PAIRS: &[(&str, &str)] = &[
    ("agdia-lmx54700", "liquid"),
    ("eiken-lmp204", "liquid"),
    ("eiken-lmp207", "dry-reagent"),
    ("eiken-lmp244", "liquid"),
    ("eiken-lmp247", "dry-reagent"),
    ("hyasen-hyb315", "lyophilized"),
    ("hyasen-hyb413", "liquid"),
    ("hyasen-hyb413", "lyophilizable"),
    ("hyasen-hyb414", "lyophilized"),
    ("jena-pcr387", "liquid"),
    ("jena-pcr393", "liquid"),
    ("jena-pcr395", "lyophilized"),
    ("jena-pcr398", "lyophilized"),
    ("jena-pcr540", "liquid"),
    ("jena-pcr541", "liquid"),
    ("jena-pcr541", "lyophilized"),
    ("meridian-mdx097", "liquid"),
    ("meridian-mdx108", "liquid"),
    ("meridian-mdx118", "lyophilized"),
    ("meridian-mdx119", "air-dryable"),
    ("meridian-mdx124", "liquid"),
    ("meridian-mdx125", "liquid"),
    ("meridian-mdx126", "air-dryable"),
    ("meridian-mdx126", "liquid"),
    ("meridian-mdx134", "liquid"),
    ("meridian-mdx135", "liquid"),
    ("meridian-mdx144", "liquid"),
    ("meridian-mdx145", "liquid"),
    ("meridian-mdx154", "liquid"),
    ("meridian-mdx155", "liquid"),
    ("neb-e1700", "liquid"),
    ("neb-e1708", "liquid"),
    ("neb-l4401", "lyophilized"),
    ("neb-m0275", "assembled-enzyme"),
    ("neb-m0374", "assembled-enzyme"),
    ("neb-m0402-m0439-rt", "assembled-enzyme"),
    ("neb-m0537", "assembled-enzyme"),
    ("neb-m0538", "assembled-enzyme"),
    ("neb-m1708", "liquid"),
    ("neb-m1712", "liquid"),
    ("neb-m1800", "liquid"),
    ("neb-m1804", "liquid"),
    ("neb-m9204", "liquid"),
    ("neb-m9205", "liquid"),
    ("nippon-dr0401", "dry-reagent"),
    ("nippon-dr0701", "dry-reagent"),
    ("nippon-heatact-fluorescence", "liquid"),
    ("nippon-heatact-turbidity", "liquid"),
    ("nippon-heatact-turbidity-visible", "liquid"),
    ("nippon-ne6041", "liquid"),
    ("nzy-md0696", "lyophilized"),
    ("nzy-md0697", "lyophilized"),
    ("optigene-dr001", "dry-reagent"),
    ("optigene-dr001-lnl", "dry-reagent"),
    ("optigene-dr004", "dry-reagent"),
    ("optigene-dr004-rt", "dry-reagent"),
    ("optigene-iso001", "liquid"),
    ("optigene-iso001-lnl", "liquid"),
    ("optigene-iso001-lyo", "lyophilized"),
    ("optigene-iso001-rt", "liquid"),
    ("optigene-iso001-rt-lyo", "lyophilized"),
    ("optigene-iso001tin", "liquid"),
    ("optigene-iso004", "liquid"),
    ("optigene-iso004-lnl", "liquid"),
    ("optigene-iso004-lyo", "lyophilized"),
    ("optigene-iso004-rt", "liquid"),
    ("optigene-iso004-rt-lyo", "lyophilized"),
    ("optigene-iso004-rt-vis", "liquid"),
    ("takara-rr385", "liquid"),
    ("thermo-a5180x", "liquid"),
    ("thermo-a56656", "assembled-enzyme"),
    ("vazyme-rp711", "liquid"),
    ("vazyme-rp712", "liquid"),
    ("yeasen-16729", "liquid"),
    ("yeasen-16730", "liquid"),
    ("yeasen-16730", "lyophilized"),
];

/// Derived compatibility pairs for the `LAMP_FORBIDDEN_READOUT_PAIRS` authority branch.
pub const LAMP_FORBIDDEN_READOUT_PAIRS: &[(&str, &str)] = &[
    ("nippon-heatact-fluorescence", "turbidity"),
    ("nippon-ne6041", "turbidity"),
    ("takara-rr385", "turbidity"),
];

/// Derived compatibility pairs for the `LAMP_FORBIDDEN_CHEMISTRY_PAIRS` authority branch.
pub const LAMP_FORBIDDEN_CHEMISTRY_PAIRS: &[(&str, &str)] = &[
    ("neb-m1712", "hydroxynaphthol-blue"),
    ("nippon-heatact-fluorescence", "turbidity-pyrophosphate"),
    ("nippon-ne6041", "turbidity-pyrophosphate"),
    ("takara-rr385", "turbidity-pyrophosphate"),
];

/// Derived readout-to-chemistry compatibility branches.
pub const LAMP_READOUT_CHEMISTRY_BRANCHES: &[(&str, &str)] = &[
    ("agarose-gel-endpoint", "other-validated"),
    ("calcein", "colorimetric"),
    ("eiken-fd-lmp221", "fluorescence"),
    ("eriochrome-black-t", "colorimetric"),
    ("hydroxynaphthol-blue", "colorimetric"),
    ("not-specified", "not-specified"),
    ("nzy-speedy-lamp-dye", "fluorescence"),
    ("other-validated", "other-validated"),
    ("ph-colorimetric", "colorimetric"),
    ("supplied-intercalating-dye", "fluorescence"),
    ("syto82", "fluorescence"),
    ("syto9", "fluorescence"),
    ("tb-green", "fluorescence"),
    ("turbidity-pyrophosphate", "turbidity"),
    ("vendor-visual-color-change", "colorimetric"),
];
