// @generated by scripts/generate-domain-vocabulary.py; do not edit.
// Goal/Modifier/Status come from Rust domain taxonomy; engine IDs come from contracts/engines.toml.
export const GOAL_IDS = ["amplify", "quantify", "genotype", "detect", "sequence", "assemble", "engineer"] as const;
export const MODIFIER_IDS = ["multiplex", "reverse-transcription", "bisulfite-conversion", "tails", "variant-masking"] as const;
export const MODULE_STATUS_IDS = ["planned", "experimental", "stable"] as const;
