// @generated by scripts/generate-foundation-contracts.py from contracts/foundation.toml; do not edit.
export const MAX_SEQUENCE_BYTES = 8388608;
export const SEQUENCE_ASSET_EXTERNALIZE_BYTES = 65536;
export const MAX_ACTION_BYTES = 12582912;
export const MAX_HTTP_BODY_BYTES = 67108864;
export const MAX_ACCOUNT_IMPORT_BYTES = 67108864;
export const MAX_PROJECT_SETTINGS_BYTES = 10485760;
export const MAX_PROJECT_NOTES_BYTES = 262144;
export const MAX_RUN_LABEL_BYTES = 1024;
export const MAX_RUN_JOB_REQUEST_BYTES = 8388608;
export const MAX_RUN_JOB_AUX_BYTES = 262144;
export const MAX_WORKER_STDOUT_BYTES = 16777216;
export const MAX_WORKER_STDERR_BYTES = 262144;
export const MAX_RUN_DOCUMENT_BYTES = 26214400;
export const MAX_ACCOUNT_PROJECT_DATA_BYTES = 58720256;
export const MAX_ACCOUNT_JOB_DATA_BYTES = 67108864;
export const MAX_BACKUP_DOCUMENT_BYTES = 67108864;
