/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["invitations_accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projects_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["projects_partial_update"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/access/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projects_access_list"];
        put?: never;
        post: operations["projects_access_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/access/{membership_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["projects_access_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/recover/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["projects_recover_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspaces_list"];
        put?: never;
        post: operations["workspaces_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/invitations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspaces_invitations_list"];
        put?: never;
        post: operations["workspaces_invitations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/invitations/{invitation_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["workspaces_invitations_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/leave/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaces_leave_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspaces_members_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/members/{membership_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["workspaces_members_destroy"];
        options?: never;
        head?: never;
        patch: operations["workspaces_members_partial_update"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/orphaned-projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspaces_orphaned_projects_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspaces_projects_list"];
        put?: never;
        post: operations["workspaces_projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CSRF: {
            readonly csrf_token: string;
        };
        Invitation: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly role: components["schemas"]["WorkspaceRoleEnum"];
            /** Format: date-time */
            readonly expires_at: string;
        };
        InvitationAcceptRequest: {
            key: string;
        };
        InvitationCreateRequest: {
            /** Format: email */
            email: string;
            /** @default member */
            role: components["schemas"]["WorkspaceRoleEnum"];
        };
        /**
         * @description * `personal` - Personal
         *     * `organization` - Organization
         * @enum {string}
         */
        KindEnum: "personal" | "organization";
        Me: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly email_verified: boolean;
            readonly mfa_enabled: boolean;
            readonly mfa_required: boolean;
            readonly mfa_authenticated: boolean;
        };
        Member: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly role: components["schemas"]["WorkspaceRoleEnum"];
            readonly active: boolean;
        };
        MemberRoleRequest: {
            role: components["schemas"]["WorkspaceRoleEnum"];
        };
        OrphanedProject: {
            /** Format: uuid */
            readonly id: string;
            readonly version: number;
        };
        PaginatedInvitationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Invitation"][];
        };
        PaginatedMemberList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Member"][];
        };
        PaginatedOrphanedProjectList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["OrphanedProject"][];
        };
        PaginatedProjectList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Project"][];
        };
        Project: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly workspace_id: string;
            readonly name: string;
            readonly description: string;
            readonly version: number;
            readonly archived: boolean;
            readonly role: components["schemas"]["ProjectRoleEnum"];
            /** Format: uuid */
            readonly owner_membership_id: string;
            readonly orphaned: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ProjectAccess: {
            /** Format: uuid */
            readonly membership_id: string;
            /** Format: email */
            readonly email: string;
            readonly role: components["schemas"]["ProjectRoleEnum"];
        };
        ProjectAccessCreateRequest: {
            /** Format: uuid */
            membership_id: string;
            role: components["schemas"]["ProjectRoleEnum"];
            version: number;
        };
        ProjectCreateRequest: {
            name: string;
            /** @default  */
            description: string;
        };
        ProjectRecoveryRequest: {
            /** Format: uuid */
            membership_id: string;
            version: number;
            reason: components["schemas"]["ReasonEnum"];
        };
        /**
         * @description * `owner` - owner
         *     * `editor` - editor
         *     * `viewer` - viewer
         * @enum {string}
         */
        ProjectRoleEnum: "owner" | "editor" | "viewer";
        ProjectUpdateRequest: {
            version: number;
            name?: string;
            description?: string;
            archived?: boolean;
        };
        /**
         * @description * `owner_removed` - owner_removed
         *     * `owner_suspended` - owner_suspended
         *     * `security_revocation` - security_revocation
         * @enum {string}
         */
        ReasonEnum: "owner_removed" | "owner_suspended" | "security_revocation";
        Workspace: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly kind: components["schemas"]["KindEnum"];
            readonly role: components["schemas"]["WorkspaceRoleEnum"];
        };
        WorkspaceCreateRequest: {
            name: string;
        };
        /**
         * @description * `owner` - Owner
         *     * `member` - Member
         * @enum {string}
         */
        WorkspaceRoleEnum: "owner" | "member";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CSRF"];
                };
            };
        };
    };
    invitations_accept_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAcceptRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["InvitationAcceptRequest"];
                "multipart/form-data": components["schemas"]["InvitationAcceptRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    projects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectUpdateRequest"];
                "multipart/form-data": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    projects_access_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectAccess"][];
                };
            };
        };
    };
    projects_access_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectAccessCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectAccessCreateRequest"];
                "multipart/form-data": components["schemas"]["ProjectAccessCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    projects_access_destroy: {
        parameters: {
            query: {
                version: number;
            };
            header?: never;
            path: {
                membership_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_recover_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectRecoveryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectRecoveryRequest"];
                "multipart/form-data": components["schemas"]["ProjectRecoveryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrphanedProject"];
                };
            };
        };
    };
    workspaces_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    workspaces_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkspaceCreateRequest"];
                "multipart/form-data": components["schemas"]["WorkspaceCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    workspaces_invitations_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInvitationList"];
                };
            };
        };
    };
    workspaces_invitations_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["InvitationCreateRequest"];
                "multipart/form-data": components["schemas"]["InvitationCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
        };
    };
    workspaces_invitations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_leave_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_members_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMemberList"];
                };
            };
        };
    };
    workspaces_members_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_members_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRoleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MemberRoleRequest"];
                "multipart/form-data": components["schemas"]["MemberRoleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    workspaces_orphaned_projects_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOrphanedProjectList"];
                };
            };
        };
    };
    workspaces_projects_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectList"];
                };
            };
        };
    };
    workspaces_projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectCreateRequest"];
                "multipart/form-data": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
}
