#!/usr/bin/env python3
"""Render the Flanking evidence ledger Markdown from canonical JSON."""
from __future__ import annotations
import argparse, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "release/FLANKING-PAIR-EVIDENCE-LEDGER.json"
OUT = ROOT / "release/FLANKING-PAIR-EVIDENCE-LEDGER.md"

def render(doc: dict) -> str:
    lines = [
        "<!-- GENERATED by scripts/generate-flanking-evidence-ledger.py; edit the JSON authority instead. -->",
        "# PCRStudio Flanking-Pair Evidence Ledger",
        "",
        f"- **Audit date:** {doc['audit_date']}",
        f"- **Engine:** `{doc['engine']}`",
        f"- **Scope:** {doc['scope']}",
        "",
    ]
    for row in doc["records"]:
        lines += [
            f"## {row['id']} — {row['area']}", "",
            f"- **Decision role:** `{row['decision_role']}`",
            f"- **Status:** `{row['status']}`",
            f"- **Claim:** {row['claim']}",
            f"- **Sources:** {'; '.join(row['sources'])}",
            "- **Implementation:** " + ", ".join(f"`{x}`" for x in row["implementation"]),
            f"- **Claim boundary:** {row['boundary']}", "",
        ]
    return "\n".join(lines).rstrip() + "\n"

def main() -> int:
    ap=argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); args=ap.parse_args()
    doc=json.loads(SRC.read_text(encoding='utf-8'))
    expected=render(doc)
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding='utf-8') != expected:
            print('FLANKING_EVIDENCE_LEDGER=STALE'); return 1
        print(f"FLANKING_EVIDENCE_LEDGER=CHECK-PASS records={len(doc['records'])}"); return 0
    OUT.write_text(expected, encoding='utf-8')
    print(f"FLANKING_EVIDENCE_LEDGER=GENERATED records={len(doc['records'])}"); return 0
if __name__ == '__main__': raise SystemExit(main())
