#!/usr/bin/env python3
"""Generate cross-language Flanking protocol identity projections from one TOML authority."""
from __future__ import annotations
import argparse, json, tomllib
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'contracts/chemistry/flanking-protocols.toml'
JSON_OUTPUTS=[
 ROOT/'tools/src/pcr_tools/data/flanking-protocol-authority.generated.json',
 ROOT/'web/src/lib/flanking-protocol-authority.generated.json',
 ROOT/'knowledge/runtime/flanking-protocol-authority.generated.json',
]
RUST_OUTPUT=ROOT/'crates/pcr-core/src/engines/flanking_protocol_ids.generated.rs'
TS_OUTPUT=ROOT/'web/src/lib/flanking-protocol-authority.generated.ts'
RUST_NAMES={
 'standard_pcr':'STANDARD_PCR_PROTOCOLS',
 'qpcr_sybr':'QPCR_PROTOCOLS',
 'rpa':'RPA_PROTOCOLS',
 'rpa_executable':'RPA_EXECUTABLE_PROTOCOLS',
 'long_range':'LONG_RANGE_PROTOCOLS',
 'digital':'DIGITAL_PROTOCOLS',
 'digital_partition_formats':'DIGITAL_PARTITION_FORMATS',
 'digital_platform_ids':'DIGITAL_PLATFORM_IDS',
 'digital_fragmentation_states':'DIGITAL_FRAGMENTATION_STATES',
 'qpcr_instrument_profiles':'QPCR_INSTRUMENT_PROFILES',
 'digital_consumable_ids':'DIGITAL_CONSUMABLE_IDS',
 'colony_protocols':'COLONY_PROTOCOLS',
 'colony_host_classes':'COLONY_HOST_CLASSES',
 'colony_preparations':'COLONY_PREPARATIONS',
 'restriction_digest_protocols':'RESTRICTION_DIGEST_PROTOCOLS',
 'restriction_dephosphorylation_protocols':'RESTRICTION_DEPHOSPHORYLATION_PROTOCOLS',
 'restriction_ligation_protocols':'RESTRICTION_LIGATION_PROTOCOLS',
}

def rendered_json(payload): return json.dumps(payload,indent=2,ensure_ascii=False,sort_keys=True)+'\n'
def rendered_rust(groups, compatibility, routing, labels, aliases):
 lines=['// @generated by scripts/generate-flanking-protocol-authority.py; do not edit.']
 for key,name in RUST_NAMES.items():
  vals=groups[key]
  lines.append(f'const {name}: &[&str] = &[')
  lines += [f'    {json.dumps(v)},' for v in vals]
  lines.append('];\n')
 pairs=[]
 for consumable, platforms in compatibility['digital_consumable_platforms'].items():
  pairs.extend((consumable, platform) for platform in platforms)
 lines.append('const DIGITAL_CONSUMABLE_PLATFORM_PAIRS: &[(&str, &str)] = &[')
 lines += [f'    ({json.dumps(consumable)}, {json.dumps(platform)}),' for consumable,platform in sorted(pairs)]
 lines.append('];\n')
 protocol_pairs=[]
 for protocol, platforms in compatibility['digital_protocol_platforms'].items():
  protocol_pairs.extend((protocol, platform) for platform in platforms)
 lines.append('const DIGITAL_PROTOCOL_PLATFORM_PAIRS: &[(&str, &str)] = &[')
 lines += [f'    ({json.dumps(protocol)}, {json.dumps(platform)}),' for protocol,platform in sorted(protocol_pairs)]
 lines.append('];\n')
 lines.append('const DIGITAL_PLATFORM_ROUTES: &[(&str, &str)] = &[')
 lines += [f'    ({json.dumps(platform)}, {json.dumps(route)}),' for platform,route in sorted(routing['digital_platforms'].items())]
 lines.append('];\n')
 lines.append('const DIGITAL_PLATFORM_CANONICAL_NAMES: &[(&str, &str)] = &[')
 lines += [f'    ({json.dumps(platform)}, {json.dumps(label)}),' for platform,label in sorted(labels['digital_platforms'].items())]
 lines.append('];\n')
 alias_pairs=[]
 for platform, names in aliases['digital_platform_names'].items():
  alias_pairs.extend((platform, name) for name in names)
 lines.append('const DIGITAL_PLATFORM_NAME_ALIASES: &[(&str, &str)] = &[')
 lines += [f'    ({json.dumps(platform)}, {json.dumps(name)}),' for platform,name in sorted(alias_pairs)]
 lines.append('];\n')
 return '\n'.join(lines)

def rendered_ts(groups, compatibility, routing, labels, aliases):
 payload=json.dumps(groups,indent=2,ensure_ascii=False,sort_keys=True)
 compat=json.dumps(compatibility['digital_consumable_platforms'],indent=2,ensure_ascii=False,sort_keys=True)
 protocol_compat=json.dumps(compatibility['digital_protocol_platforms'],indent=2,ensure_ascii=False,sort_keys=True)
 platform_routes=json.dumps(routing['digital_platforms'],indent=2,ensure_ascii=False,sort_keys=True)
 platform_labels=json.dumps(labels['digital_platforms'],indent=2,ensure_ascii=False,sort_keys=True)
 platform_aliases=json.dumps(aliases['digital_platform_names'],indent=2,ensure_ascii=False,sort_keys=True)
 return (
  '// @generated by scripts/generate-flanking-protocol-authority.py; do not edit.\n'
  f'export const FLANKING_PROTOCOL_GROUPS = {payload} as const;\n\n'
  f'export const DIGITAL_CONSUMABLE_PLATFORMS = {compat} as const;\n\n'
  f'export const DIGITAL_PROTOCOL_PLATFORMS = {protocol_compat} as const;\n\n'
  f'export const DIGITAL_PLATFORM_ROUTES = {platform_routes} as const;\n\n'
  f'export const DIGITAL_PLATFORM_LABELS = {platform_labels} as const;\n\n'
  f'export const DIGITAL_PLATFORM_NAME_ALIASES = {platform_aliases} as const;\n\n'
  'export type QpcrInstrumentProfile = typeof FLANKING_PROTOCOL_GROUPS.qpcr_instrument_profiles[number];\n'
  'export type DigitalConsumableId = typeof FLANKING_PROTOCOL_GROUPS.digital_consumable_ids[number];\n'
  'export type DigitalPlatformId = typeof FLANKING_PROTOCOL_GROUPS.digital_platform_ids[number];\n'
  'export type ColonyHostClass = typeof FLANKING_PROTOCOL_GROUPS.colony_host_classes[number];\n'
  'export type ColonyPreparation = typeof FLANKING_PROTOCOL_GROUPS.colony_preparations[number];\n'
 )
def write_or_check(path,text,check,drift):
 if check:
  if not path.is_file() or path.read_text(encoding='utf-8')!=text: drift.append(path.relative_to(ROOT).as_posix())
 else:
  path.parent.mkdir(parents=True,exist_ok=True); path.write_text(text,encoding='utf-8',newline='\n')

def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); args=ap.parse_args()
 raw=tomllib.loads(SOURCE.read_text(encoding='utf-8')); groups=raw.get('groups'); compatibility=raw.get('compatibility'); routing=raw.get('routing'); routing_evidence=raw.get('routing_evidence', {}); labels=raw.get('labels'); aliases=raw.get('aliases'); provenance=raw.get('provenance')
 if not isinstance(groups,dict): raise SystemExit('flanking protocol authority missing [groups]')
 if not isinstance(compatibility,dict) or not isinstance(compatibility.get('digital_consumable_platforms'),dict) or not isinstance(compatibility.get('digital_protocol_platforms'),dict): raise SystemExit('flanking protocol authority missing digital compatibility maps')
 if not isinstance(routing,dict) or not isinstance(routing.get('digital_platforms'),dict): raise SystemExit('flanking protocol authority missing [routing.digital_platforms]')
 if not isinstance(labels,dict) or not isinstance(labels.get('digital_platforms'),dict): raise SystemExit('flanking protocol authority missing [labels.digital_platforms]')
 if not isinstance(aliases,dict) or not isinstance(aliases.get('digital_platform_names'),dict): raise SystemExit('flanking protocol authority missing [aliases.digital_platform_names]')
 if not isinstance(provenance,dict): raise SystemExit('flanking protocol authority missing [provenance.*]')
 missing=sorted(set(RUST_NAMES)-set(groups)); extra=sorted(set(groups)-set(RUST_NAMES))
 if missing or extra: raise SystemExit(f'authority groups mismatch missing={missing} extra={extra}')
 for key,vals in groups.items():
  if not isinstance(vals,list) or any(not isinstance(v,str) or not v for v in vals): raise SystemExit(f'{key} must be non-empty string list')
  if len(vals)!=len(set(vals)): raise SystemExit(f'{key} contains duplicate ids')
 if not set(groups['rpa_executable']) <= set(groups['rpa']): raise SystemExit('rpa_executable must be subset of rpa')
 consumable_map=compatibility['digital_consumable_platforms']
 if set(consumable_map) != set(groups['digital_consumable_ids']): raise SystemExit('digital consumable compatibility keys must exactly match digital_consumable_ids')
 for consumable,platforms in consumable_map.items():
  if not isinstance(platforms,list) or not platforms or any(p not in groups['digital_platform_ids'] for p in platforms): raise SystemExit(f'invalid digital consumable platform mapping: {consumable}')
 protocol_map=compatibility['digital_protocol_platforms']
 if any(protocol not in groups['digital'] or protocol == 'not-selected' for protocol in protocol_map): raise SystemExit('digital protocol compatibility keys must be named digital protocols')
 for protocol,platforms in protocol_map.items():
  if not isinstance(platforms,list) or not platforms or any(p not in groups['digital_platform_ids'] for p in platforms): raise SystemExit(f'invalid digital protocol platform mapping: {protocol}')
 platform_routes=routing['digital_platforms']
 expected_routes={'dye-flanking','dye-flanking-unresolved-chemistry','pair-probe','custom-validated'}
 if set(platform_routes) != set(groups['digital_platform_ids']): raise SystemExit('digital platform routing ids must exactly match digital_platform_ids')
 if any(route not in expected_routes for route in platform_routes.values()): raise SystemExit('digital platform routing contains unsupported route class')
 if platform_routes.get('other-validated') != 'custom-validated': raise SystemExit('other-validated must retain custom-validated routing')
 platform_labels=labels['digital_platforms']; platform_aliases=aliases['digital_platform_names']
 expected_named_platforms=set(groups['digital_platform_ids'])-{'other-validated'}
 if set(platform_labels)!=expected_named_platforms: raise SystemExit(f'digital platform label ids mismatch missing={sorted(expected_named_platforms-set(platform_labels))} extra={sorted(set(platform_labels)-expected_named_platforms)}')
 if set(platform_aliases)!=expected_named_platforms: raise SystemExit(f'digital platform alias ids mismatch missing={sorted(expected_named_platforms-set(platform_aliases))} extra={sorted(set(platform_aliases)-expected_named_platforms)}')
 for platform,label in platform_labels.items():
  if not isinstance(label,str) or not label.strip(): raise SystemExit(f'invalid digital platform label: {platform}')
 for platform,names in platform_aliases.items():
  if not isinstance(names,list) or not names or any(not isinstance(name,str) or not name.strip() or name != name.casefold() for name in names): raise SystemExit(f'invalid digital platform aliases: {platform}')
  if platform_labels[platform].casefold() not in names: raise SystemExit(f'canonical digital platform label must appear in aliases: {platform}')
 expected_provenance=set()
 for key in ('standard_pcr','qpcr_sybr','rpa','long_range','digital','colony_protocols','restriction_digest_protocols','restriction_dephosphorylation_protocols','restriction_ligation_protocols'):
  expected_provenance.update(groups[key])
 expected_provenance -= {'not-selected','custom-sop','none'}
 route_sources=set()
 route_map=(routing_evidence or {}).get('digital_platforms', {}) if isinstance(routing_evidence,dict) else {}
 if route_map and set(route_map) - set(groups['digital_platform_ids']): raise SystemExit('routing evidence contains unknown digital platform id')
 for platform,source_ids in route_map.items():
  if not isinstance(source_ids,list) or not source_ids or any(not isinstance(source_id,str) or not source_id for source_id in source_ids): raise SystemExit(f'invalid routing evidence list: {platform}')
  route_sources.update(source_ids)
 expected_provenance.update(route_sources)
 if set(provenance) != expected_provenance: raise SystemExit(f'provenance ids mismatch missing={sorted(expected_provenance-set(provenance))} extra={sorted(set(provenance)-expected_provenance)}')
 for protocol_id,row in provenance.items():
  if not isinstance(row,dict) or not str(row.get('url','')).startswith('https://'): raise SystemExit(f'invalid provenance locator: {protocol_id}')
  if row.get('snapshot_status') != 'canonical-claim-snapshot-pinned': raise SystemExit(f'provenance source must be claim-snapshotted for {protocol_id}')
  if row.get('snapshot_registry') != 'knowledge/sources/flanking-source-snapshots.json': raise SystemExit(f'provenance snapshot registry drift: {protocol_id}')
  digest=str(row.get('claim_snapshot_sha256',''))
  if len(digest)!=64 or any(ch not in '0123456789abcdef' for ch in digest): raise SystemExit(f'invalid claim snapshot digest: {protocol_id}')
  if row.get('availability_scope') != 'not-asserted': raise SystemExit(f'provenance availability scope must remain non-assertive for {protocol_id}')
 payload={'schema_version':raw['schema_version'],'authority':raw['authority'],'effective_date':raw['effective_date'],'source':'contracts/chemistry/flanking-protocols.toml','groups':groups,'compatibility':compatibility,'routing':routing,'routing_evidence':routing_evidence,'labels':labels,'aliases':aliases,'provenance':provenance}
 drift=[]
 for out in JSON_OUTPUTS: write_or_check(out,rendered_json(payload),args.check,drift)
 write_or_check(RUST_OUTPUT,rendered_rust(groups,compatibility,routing,labels,aliases),args.check,drift)
 write_or_check(TS_OUTPUT,rendered_ts(groups,compatibility,routing,labels,aliases),args.check,drift)
 if drift:
  print('FLANKING_PROTOCOL_AUTHORITY_DRIFT'); print('\n'.join(drift)); return 1
 print(f"FLANKING_PROTOCOL_AUTHORITY={'CHECK-PASS' if args.check else 'GENERATED'} groups={len(groups)}")
 return 0
if __name__=='__main__': raise SystemExit(main())
