#!/usr/bin/env python3
"""Generate cross-language Loop Set/LAMP authority projections from one JSON source."""
from __future__ import annotations
import argparse, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'contracts/chemistry/lamp-protocols.json'
JSON_OUTPUTS=[
 ROOT/'tools/src/pcr_tools/data/lamp-protocol-authority.generated.json',
 ROOT/'web/src/lib/lamp-protocol-authority.generated.json',
 ROOT/'knowledge/runtime/lamp-protocol-authority.generated.json',
]
TS_OUTPUT=ROOT/'web/src/lib/lamp-protocol-authority.generated.ts'
RUST_OUTPUT=ROOT/'crates/pcr-core/src/engines/lamp_protocol_ids.generated.rs'
RUST_GROUPS={
 'protocols':'LAMP_PROTOCOLS','readouts':'LAMP_READOUTS','readout_chemistries':'LAMP_READOUT_CHEMISTRIES',
 'sample_matrices':'LAMP_SAMPLE_MATRICES','sample_preparations':'LAMP_SAMPLE_PREPARATIONS','formulations':'LAMP_FORMULATIONS',
 'confirmation_modes':'LAMP_CONFIRMATION_MODES','detection_topologies':'LAMP_DETECTION_TOPOLOGIES','design_intents':'LAMP_DESIGN_INTENTS',
 'loop_policies':'LAMP_LOOP_POLICIES','design_stages':'LAMP_DESIGN_STAGES','parameter_sets':'PARAMETER_SETS',
 'geometry_profiles':'LAMP_GEOMETRY_PROFILES','inner_linkers':'LAMP_INNER_LINKERS','instrument_profiles':'LAMP_INSTRUMENT_PROFILES',
 'carryover_strategies':'LAMP_CARRYOVER_STRATEGIES','reconstitution_options':'LAMP_RECONSTITUTION_OPTIONS',
 'specificity_additives':'LAMP_SPECIFICITY_ADDITIVES','acceleration_additives':'LAMP_ACCELERATION_ADDITIVES',
 'primer_kinetics_profiles':'LAMP_PRIMER_KINETICS_PROFILES','preincubation_strategies':'LAMP_PREINCUBATION_STRATEGIES',
 'sample_buffer_types':'LAMP_SAMPLE_BUFFER_TYPES','mutation_anchors':'LAMP_MUTATION_ANCHORS','fixed_primer_roles':'LAMP_FIXED_PRIMER_ROLES',
}

def text_json(payload): return json.dumps(payload,indent=2,ensure_ascii=False,sort_keys=True)+'\n'

def validate(payload:dict)->None:
 if payload.get('schema_version')!='1.0.0': raise SystemExit('unexpected LAMP authority schema version')
 groups=payload.get('groups'); protocols=payload.get('protocols'); auto=payload.get('automatic_judgment')
 if not isinstance(groups,dict) or not isinstance(protocols,dict): raise SystemExit('LAMP authority missing groups/protocols')
 missing=sorted(set(RUST_GROUPS)-set(groups)); extra=sorted(set(groups)-set(RUST_GROUPS))
 if missing or extra: raise SystemExit(f'LAMP authority group mismatch missing={missing} extra={extra}')
 for key,vals in groups.items():
  if not isinstance(vals,list) or any(not isinstance(v,str) or not v for v in vals): raise SystemExit(f'{key} must be string list')
  if len(vals)!=len(set(vals)): raise SystemExit(f'{key} contains duplicates')
 protocol_group=groups.get('protocols',[])
 if not protocol_group or protocol_group[0]!='not-selected' or len(protocol_group)!=len(set(protocol_group)) or set(protocol_group[1:])!=set(protocols):
  raise SystemExit('protocol group must contain each protocol exactly once after not-selected')
 for pid,rec in protocols.items():
  for field in ('selection','vendor','kit_id','protocol_kind','source_identity','source_url','source_reviewed_date','supports_dna','supports_rna','formats','recommended_readouts','sequence_decision_impact'):
   if field not in rec: raise SystemExit(f'{pid} missing {field}')
  if rec['sequence_decision_impact']!='none': raise SystemExit(f'{pid} bench protocol cannot change sequence ranking')
  if not str(rec['source_url']).startswith('https://'): raise SystemExit(f'{pid} requires HTTPS source URL')
 if not isinstance(auto,dict) or auto.get('gc_rich_min_percent_inclusive')!=60.0 or auto.get('at_rich_max_percent_inclusive')!=45.0:
  raise SystemExit('PrimerExplorer automatic judgment authority must preserve <=45 and >=60 boundaries')
 if 'fixed-primer-anchor' not in groups['design_intents'] or 'mutation-anchored-specific' not in groups['design_intents']:
  raise SystemExit('advanced LAMP design intents missing')

def rendered_rust(payload:dict)->str:
 groups=payload['groups']; protocols=payload['protocols']; branch=payload['compatibility']['readout_chemistry_branch']; lines=['// @generated by scripts/generate-lamp-protocol-authority.py; do not edit.']
 for key,name in RUST_GROUPS.items():
  lines.append(f'/// Closed vocabulary for the `{key}` authority group.')
  lines.append(f'pub const {name}: &[&str] = &['); lines += [f'    {json.dumps(v)},' for v in groups[key]]; lines.append('];\n')
 dna_only=[p for p,r in protocols.items() if r.get('supports_dna') and not r.get('supports_rna')]
 rna_only=[p for p,r in protocols.items() if r.get('supports_rna') and not r.get('supports_dna')]
 for name,vals in [('LAMP_DNA_ONLY_PROTOCOLS',dna_only),('LAMP_RNA_ONLY_PROTOCOLS',rna_only)]:
  lines.append(f'/// Derived protocol vocabulary for the `{name}` compatibility branch.')
  lines.append(f'pub const {name}: &[&str] = &['); lines += [f'    {json.dumps(v)},' for v in vals]; lines.append('];\n')
 direct=[]; forms=[]; forbidden_r=[]; forbidden_c=[]
 for pid,rec in protocols.items():
  for matrix in rec.get('direct_sample_matrices',[]): direct.append((pid,matrix))
  for form in rec.get('formats',[]): forms.append((pid,form))
  for readout in rec.get('forbidden_readouts',{}): forbidden_r.append((pid,readout))
  for chem in rec.get('forbidden_readout_chemistries',{}): forbidden_c.append((pid,chem))
 for name,pairs in [('LAMP_DIRECT_SAMPLE_PAIRS',direct),('LAMP_PROTOCOL_FORMULATION_PAIRS',forms),('LAMP_FORBIDDEN_READOUT_PAIRS',forbidden_r),('LAMP_FORBIDDEN_CHEMISTRY_PAIRS',forbidden_c)]:
  lines.append(f'/// Derived compatibility pairs for the `{name}` authority branch.')
  lines.append(f'pub const {name}: &[(&str, &str)] = &['); lines += [f'    ({json.dumps(a)}, {json.dumps(b)}),' for a,b in sorted(pairs)]; lines.append('];\n')
 lines.append('/// Derived readout-to-chemistry compatibility branches.')
 lines.append('pub const LAMP_READOUT_CHEMISTRY_BRANCHES: &[(&str, &str)] = &['); lines += [f'    ({json.dumps(a)}, {json.dumps(b)}),' for a,b in sorted(branch.items())]; lines.append('];\n')
 return '\n'.join(lines)

def rendered_ts(payload:dict)->str:
 # JSON object is generated too; TS keeps literal ID unions and convenient selectors.
 g=payload['groups']
 lines=['// @generated by scripts/generate-lamp-protocol-authority.py; do not edit.', 'import authority from "./lamp-protocol-authority.generated.json";', 'export const LAMP_AUTHORITY = authority;']
 for key in RUST_GROUPS:
  cname='LAMP_'+key.upper()
  lines.append(f'export const {cname} = {json.dumps(g[key],ensure_ascii=False)} as const;')
 lines += [
  'export type LampProtocolId = typeof LAMP_PROTOCOLS[number];',
  'export type LampReadout = typeof LAMP_READOUTS[number];',
  'export type LampReadoutChemistry = typeof LAMP_READOUT_CHEMISTRIES[number];',
  'export type LampFormulation = typeof LAMP_FORMULATIONS[number];',
  'export type LampDesignIntent = typeof LAMP_DESIGN_INTENTS[number];',
  'export type LampLoopPolicy = typeof LAMP_LOOP_POLICIES[number];',
  'export type LampDesignStage = typeof LAMP_DESIGN_STAGES[number];',
  'export type LampMutationAnchor = typeof LAMP_MUTATION_ANCHORS[number];',
  'export const LAMP_PROTOCOL_METADATA = authority.protocols;',
  'export const LAMP_AUTOMATIC_JUDGMENT = authority.automatic_judgment;',
  'export const LAMP_SCREENING_COHORT = authority.screening_cohort;',
 ]
 return '\n'.join(lines)+'\n'

def write_or_check(path:Path,text:str,check:bool,drift:list[str])->None:
 if check:
  if not path.is_file() or path.read_text(encoding='utf-8')!=text: drift.append(path.relative_to(ROOT).as_posix())
 else:
  path.parent.mkdir(parents=True,exist_ok=True); path.write_text(text,encoding='utf-8',newline='\n')

def main()->None:
 ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); args=ap.parse_args()
 payload=json.loads(SOURCE.read_text(encoding='utf-8')); validate(payload)
 drift=[]; j=text_json(payload)
 for path in JSON_OUTPUTS: write_or_check(path,j,args.check,drift)
 write_or_check(TS_OUTPUT,rendered_ts(payload),args.check,drift)
 write_or_check(RUST_OUTPUT,rendered_rust(payload),args.check,drift)
 if drift: raise SystemExit('LAMP_PROTOCOL_AUTHORITY=CHECK-DRIFT '+','.join(drift))
 print(f'LAMP_PROTOCOL_AUTHORITY={"CHECK-PASS" if args.check else "GENERATED"} protocols={len(payload["protocols"])} groups={len(payload["groups"])}')
if __name__=='__main__': main()
