#!/usr/bin/env python3
"""Generate browser closed-vocabulary IDs from their canonical domain authorities.

Goal/Modifier/Status are domain vocabulary owned by Rust taxonomy.rs. Engine IDs
are execution-contract vocabulary owned by contracts/engines.toml. This script
keeps the browser parser from maintaining a second hand-written registry.
"""
from __future__ import annotations

import argparse
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUST = ROOT / "crates/pcr-core/src/taxonomy.rs"
ENGINES = ROOT / "contracts/engines.toml"
OUT = ROOT / "web/src/lib/contracts/domain-vocabulary.generated.ts"


def enum_variants(source: str, name: str) -> list[str]:
    marker = f"pub enum {name} {{"
    start = source.find(marker)
    if start < 0:
        raise ValueError(f"missing Rust enum {name}")
    body = start + len(marker)
    depth = 1
    index = body
    while index < len(source) and depth:
        char = source[index]
        if char == "{": depth += 1
        elif char == "}": depth -= 1
        index += 1
    if depth:
        raise ValueError(f"unterminated Rust enum {name}")
    variants: list[str] = []
    for line in source[body:index-1].splitlines():
        line = line.strip()
        if not line or line.startswith("//") or line.startswith("#["):
            continue
        match = re.match(r"^([A-Z][A-Za-z0-9_]*)\s*[,({]", line)
        if match:
            variants.append(match.group(1))
    if not variants:
        raise ValueError(f"empty Rust enum {name}")
    return variants


def kebab(value: str) -> str:
    return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", value).lower()


def ts_tuple(name: str, values: list[str]) -> str:
    rendered = ", ".join(f'"{value}"' for value in values)
    return f"export const {name} = [{rendered}] as const;\n"


def render() -> str:
    source = RUST.read_text(encoding="utf-8")
    goals = [kebab(v) for v in enum_variants(source, "Goal")]
    modifiers = [kebab(v) for v in enum_variants(source, "Modifier")]
    statuses = [kebab(v) for v in enum_variants(source, "Status")]
    with ENGINES.open("rb") as handle:
        raw = tomllib.load(handle)
    contract_engines = sorted(str(row["id"]) for row in raw.get("engine") or [])
    if len(contract_engines) != len(set(contract_engines)) or not contract_engines:
        raise ValueError("contracts/engines.toml contains an empty or duplicate engine registry")
    return (
        "// @generated by scripts/generate-domain-vocabulary.py; do not edit.\n"
        "// Goal/Modifier/Status come from Rust domain taxonomy; engine IDs come from contracts/engines.toml.\n"
        + ts_tuple("GOAL_IDS", goals)
        + ts_tuple("MODIFIER_IDS", modifiers)
        + ts_tuple("MODULE_STATUS_IDS", statuses)
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != rendered:
            print("DOMAIN_VOCABULARY_GENERATED_DRIFT")
            return 1
        print("DOMAIN_VOCABULARY=CHECK-PASS")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8", newline="\n")
    print("DOMAIN_VOCABULARY=GENERATED")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
