#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT/'contracts/multiplex-capabilities.json'
JSON_OUTS=[
 ROOT/'tools/src/pcr_tools/data/multiplex-capabilities.generated.json',
 ROOT/'crates/pcr-core/generated/multiplex-capabilities.generated.json',
 ROOT/'web/src/lib/multiplex-capabilities.generated.json',
 ROOT/'knowledge/runtime/multiplex-capabilities.generated.json',
]
RUST_OUT=ROOT/'crates/pcr-core/src/engines/digital_multiplex_authority.generated.rs'

def rendered()->str:
 data=json.loads(SRC.read_text(encoding='utf-8'))
 data['_projection']={'canonical_source':'contracts/multiplex-capabilities.json','canonical_sha256':hashlib.sha256(SRC.read_bytes()).hexdigest(),'generated_by':'scripts/generate-multiplex-capabilities.py'}
 return json.dumps(data,indent=2,sort_keys=True,ensure_ascii=False)+'\n'
def rendered_rust()->str:
 data=json.loads(SRC.read_text(encoding='utf-8'))
 rows=data.get('platform_authorities') or {}
 lines=[
  '// @generated by scripts/generate-multiplex-capabilities.py; do not edit.',
  '#[derive(Debug, Clone, Copy)]',
  '/// Source-backed capability limits for one digital multiplex platform.',
  'pub struct DigitalMultiplexPlatformAuthority {',
  '    /// Human-readable platform family.',
  "    pub family: &'static str,",
  '    /// Number of independently detected channels.',
  '    pub detection_channels: usize,',
  '    /// Maximum target count supported by the reviewed authority.',
  '    pub multiplex_target_bound: usize,',
  '    /// Supported multiplex representation modes.',
  "    pub modes: &'static [&'static str],",
  '}',
  '',
  '/// Resolve a platform identifier to its reviewed capability authority.',
  "pub fn digital_multiplex_platform_authority(id: &str) -> Option<DigitalMultiplexPlatformAuthority> {",
  '    match id {',
 ]
 for key,row in sorted(rows.items()):
  modes=', '.join(json.dumps(str(x)) for x in row.get('modes') or [])
  lines.append(f'        {json.dumps(key)} => Some(DigitalMultiplexPlatformAuthority {{ family: {json.dumps(str(row.get("family") or key))}, detection_channels: {int(row.get("detection_channels") or 0)}, multiplex_target_bound: {int(row.get("multiplex_target_bound") or 0)}, modes: &[{modes}] }}),')
 lines += ['        _ => None,','    }','}','']
 return '\n'.join(lines)

def main()->int:
 ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); a=ap.parse_args(); text=rendered(); rust=rendered_rust()
 if a.check:
  stale=[p for p in JSON_OUTS if not p.exists() or p.read_text(encoding='utf-8')!=text]
  if not RUST_OUT.exists() or RUST_OUT.read_text(encoding='utf-8')!=rust: stale.append(RUST_OUT)
  if stale:
   [print('multiplex capability artifact is stale:',p.relative_to(ROOT)) for p in stale]; return 1
  print('multiplex capability artifacts: PASS'); return 0
 for p in JSON_OUTS:
  p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8'); print(p.relative_to(ROOT))
 RUST_OUT.write_text(rust,encoding='utf-8'); print(RUST_OUT.relative_to(ROOT))
 return 0
if __name__=='__main__': raise SystemExit(main())
