#!/usr/bin/env python3
"""Generate the unified engine-authority projections for PCRStudio.

All engines are governed through one authority registry.  Domain-specific
protocol formats (currently Flanking and LAMP) keep their specialized parsers,
but they are exported through the same Python/Web authority surface.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERIC_SPECS = {
    "assembly": ROOT / "contracts/chemistry/assembly-protocols.json",
    "consensus": ROOT / "contracts/chemistry/consensus-profiles.json",
    "discriminating": ROOT / "contracts/chemistry/discriminating-protocols.json",
    "inverse": ROOT / "contracts/chemistry/inverse-pcr-protocols.json",
    "mutagenesis": ROOT / "contracts/chemistry/mutagenesis-protocols.json",
    "nested": ROOT / "contracts/chemistry/nested-protocols.json",
    "probe": ROOT / "contracts/chemistry/qpcr-probe-protocols.json",
    "race": ROOT / "contracts/chemistry/race-protocols.json",
    "sequencing": ROOT / "contracts/chemistry/sequencing-profiles.json",
    "tiling": ROOT / "contracts/chemistry/tiling-protocols.json",
}
SPECIALIZED = {
    "flanking": {
        "source": "contracts/chemistry/flanking-protocols.toml",
        "generated": "flanking-protocol-authority.generated.json",
        "generator": "scripts/generate-flanking-protocol-authority.py",
    },
    "lamp": {
        "source": "contracts/chemistry/lamp-protocols.json",
        "generated": "lamp-protocol-authority.generated.json",
        "generator": "scripts/generate-lamp-protocol-authority.py",
    },
}


def cname(text: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", text.upper()).strip("_")


def jtext(payload: dict) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def validate_generic(name: str, payload: dict) -> None:
    if payload.get("schema_version") != "1.0.0":
        raise SystemExit(f"{name}: unexpected schema version")
    if not payload.get("authority_id") or not payload.get("reviewed_date"):
        raise SystemExit(f"{name}: authority identity/review date missing")
    if not isinstance(payload.get("groups"), dict) or not isinstance(payload.get("records"), dict):
        raise SystemExit(f"{name}: groups/records missing")
    if name == "discriminating":
        mismatch = payload.get("mismatch_model")
        if not isinstance(mismatch, dict) or not isinstance(mismatch.get("model_id"), str) or not mismatch["model_id"]:
            raise SystemExit("discriminating: mismatch_model.model_id is required")
    for group, values in payload["groups"].items():
        if not isinstance(values, list) or any(not isinstance(value, str) or not value for value in values):
            raise SystemExit(f"{name}/{group}: group values must be non-empty strings")
        if len(values) != len(set(values)):
            raise SystemExit(f"{name}/{group}: duplicate group value")
    for record_id, record in payload["records"].items():
        required = (
            "kind", "selection", "execution_status", "source_identity",
            "source_reviewed_date", "lifecycle", "sequence_decision_impact",
        )
        for field in required:
            if field not in record:
                raise SystemExit(f"{name}/{record_id}: missing {field}")
        if record.get("source_kind") == "caller-supplied-sop":
            if "source_url" in record:
                raise SystemExit(f"{name}/{record_id}: caller-supplied SOP must not have a pseudo source_url")
            if not record.get("source_revision_required") or not record.get("source_sha256_required"):
                raise SystemExit(f"{name}/{record_id}: caller-supplied SOP must require revision and SHA-256")
        elif not str(record.get("source_url", "")).startswith("https://"):
            raise SystemExit(f"{name}/{record_id}: source_url must be HTTPS")


def rust_projection(name: str, payload: dict) -> str:
    packed = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    lines = [
        f"// @generated by scripts/generate-engine-authorities.py for {name}; do not edit.",
        "/// Stable identity of this reviewed engine authority.",
        f"pub const {cname(name)}_AUTHORITY_ID: &str = {json.dumps(payload['authority_id'])};",
        "/// Date on which this authority snapshot was reviewed.",
        f"pub const {cname(name)}_AUTHORITY_REVIEWED_DATE: &str = {json.dumps(payload['reviewed_date'])};",
        "/// Canonical authority payload embedded for runtime provenance.",
        f"pub const {cname(name)}_AUTHORITY_JSON: &str = r#\"{packed}\"#;",
    ]
    if name == "discriminating":
        lines.append(
            "/// Stable identity of the evidence-scoped mismatch model.",
        )
        lines.append(
            f"pub const DISCRIMINATING_MISMATCH_MODEL_ID: &str = {json.dumps(payload['mismatch_model']['model_id'])};"
        )
    for group, values in payload.get("groups", {}).items():
        lines.append(f"/// Closed vocabulary for the `{group}` authority group.")
        lines.append(f"pub const {cname(name)}_{cname(group)}: &[&str] = &[")
        lines.extend(f"    {json.dumps(value)}," for value in values)
        lines.append("];" )
    return "\n".join(lines) + "\n"


def ts_projection(payloads: dict[str, dict]) -> str:
    all_domains = [*sorted(payloads), *sorted(SPECIALIZED)]
    lines = ["// @generated by scripts/generate-engine-authorities.py; do not edit."]
    for name in all_domains:
        if name == "flanking":
            generated = "flanking-protocol-authority.generated.json"
        elif name == "lamp":
            generated = "lamp-protocol-authority.generated.json"
        else:
            generated = f"{name}-authority.generated.json"
        lines.append(f'import {name}Authority from "./{generated}";')
    lines.append("")
    for name in all_domains:
        lines.append(f"export const {cname(name)}_AUTHORITY = {name}Authority;")
        payload = payloads.get(name)
        if payload:
            for group, values in payload.get("groups", {}).items():
                lines.append(f"export const {cname(name)}_{cname(group)} = {json.dumps(values, ensure_ascii=False)} as const;")
            if name == "discriminating":
                lines.append(
                    f"export const DISCRIMINATING_MISMATCH_MODEL_ID = {json.dumps(payload['mismatch_model']['model_id'])} as const;"
                )
        lines.append("")
    return "\n".join(lines)


def python_registry() -> str:
    all_domains = [*sorted(GENERIC_SPECS), *sorted(SPECIALIZED)]
    lines = [
        '"""Generated unified scientific-authority loader for all PCRStudio engines."""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "from importlib.resources import files",
        "from typing import Any",
        "",
        "",
        "def _load(filename: str) -> dict[str, Any]:",
        '    return json.loads(files("pcr_tools").joinpath(f"data/{filename}").read_text(encoding="utf-8"))',
        "",
    ]
    lines.append("")
    for name in all_domains:
        filename = SPECIALIZED[name]["generated"] if name in SPECIALIZED else f"{name}-authority.generated.json"
        lines.append(f'{cname(name)}_AUTHORITY = _load("{filename}")')
    lines.extend([
        "",
        "",
        "def record(authority: dict[str, Any], record_id: str) -> dict[str, Any]:",
        "    try:",
        '        return dict(authority["records"][record_id])',
        "    except KeyError as exc:",
        '        raise ValueError(f"unknown authority record `{record_id}`") from exc',
        "",
    ])
    return "\n".join(lines)


def graph(payloads: dict[str, dict]) -> dict:
    outputs: list[str] = [
        "tools/src/pcr_tools/registries/authorities.py",
        "web/src/lib/engine-authorities.generated.ts",
    ]
    sources: list[str] = []
    for name, path in sorted(GENERIC_SPECS.items()):
        sources.append(path.relative_to(ROOT).as_posix())
        outputs.extend([
            f"tools/src/pcr_tools/data/{name}-authority.generated.json",
            f"web/src/lib/{name}-authority.generated.json",
            f"knowledge/runtime/{name}-authority.generated.json",
            f"crates/pcr-core/src/engines/{name}_authority.generated.rs",
        ])
    for info in SPECIALIZED.values():
        sources.append(info["source"])
    return {
        "schema_version": "1.0.0",
        "authority_id": "pcrstudio-current-engine-authority-registry",
        "generator": "scripts/generate-engine-authorities.py",
        "specialized_generators": [SPECIALIZED[name]["generator"] for name in sorted(SPECIALIZED)],
        "sources": sorted(sources),
        "all_generated_outputs": sorted(outputs),
        "authority_domains": sorted([*payloads, *SPECIALIZED]),
    }


def emit(path: Path, text: str, *, check: bool, drift: list[str]) -> None:
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            drift.append(path.relative_to(ROOT).as_posix())
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    drift: list[str] = []
    payloads: dict[str, dict] = {}
    for name, path in sorted(GENERIC_SPECS.items()):
        payload = json.loads(path.read_text(encoding="utf-8"))
        validate_generic(name, payload)
        payloads[name] = payload
        rendered = jtext(payload)
        for rel in (
            f"tools/src/pcr_tools/data/{name}-authority.generated.json",
            f"web/src/lib/{name}-authority.generated.json",
            f"knowledge/runtime/{name}-authority.generated.json",
        ):
            emit(ROOT / rel, rendered, check=args.check, drift=drift)
        emit(
            ROOT / f"crates/pcr-core/src/engines/{name}_authority.generated.rs",
            rust_projection(name, payload),
            check=args.check,
            drift=drift,
        )
    # Specialized projections are generated by their domain parsers, but the
    # unified registry requires them to be present and current.
    for name, info in SPECIALIZED.items():
        for base in ("tools/src/pcr_tools/data", "web/src/lib", "knowledge/runtime"):
            path = ROOT / base / info["generated"]
            if not path.is_file():
                drift.append(path.relative_to(ROOT).as_posix())
    emit(ROOT / "web/src/lib/engine-authorities.generated.ts", ts_projection(payloads), check=args.check, drift=drift)
    emit(ROOT / "tools/src/pcr_tools/registries/authorities.py", python_registry(), check=args.check, drift=drift)
    emit(ROOT / "contracts/engine-authority-generated-graph.json", jtext(graph(payloads)), check=args.check, drift=drift)
    if drift:
        raise SystemExit("ENGINE_AUTHORITY=CHECK-DRIFT " + ",".join(sorted(set(drift))))
    print(
        "ENGINE_AUTHORITY=" + ("CHECK-PASS" if args.check else "GENERATED")
        + " domains=" + str(len(payloads) + len(SPECIALIZED))
    )


if __name__ == "__main__":
    main()
