#!/usr/bin/env python3
"""Generate PCRStudio operational policy projections.

The canonical source is ``contracts/operations.toml``. Prometheus-compatible
alert rules and the machine-readable runtime summary are generated projections;
operators may import the rules into any Prometheus-compatible monitoring stack.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "contracts/operations.toml"
RUNTIME = ROOT / "knowledge/runtime/operations.generated.json"
ALERTS = ROOT / "ops/prometheus/pcrstudio-alerts.yml"
DIAGNOSTICS = ROOT / "crates/pcr-server/src/diagnostics.rs"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def validate(data: dict[str, Any]) -> None:
    if data.get("release_line") != "CURRENT":
        raise ValueError("operations release_line must be CURRENT")
    backup = data.get("backup") or {}
    for key in ("target_rpo_hours", "target_rto_hours", "default_retention_days"):
        if not isinstance(backup.get(key), int) or int(backup[key]) <= 0:
            raise ValueError(f"operations backup.{key} must be a positive integer")
    if backup.get("off_host_copy_required_for_host_loss_dr") is not True:
        raise ValueError("host-loss disaster recovery must explicitly require an off-host copy")
    storage = data.get("storage") or {}
    if storage.get("mode") != "dedicated-host-budget":
        raise ValueError("operations storage policy must use the dedicated-host budget")
    if storage.get("application_budget_gib") != 20:
        raise ValueError("operations storage budget must remain 20 GiB")
    if storage.get("runner_stop_headroom_gib") != 4:
        raise ValueError("operations storage policy must reserve 4 GiB before pausing scientific work")
    if storage.get("minimum_host_free_gib") != 8 or storage.get("critical_host_free_gib") != 4:
        raise ValueError("operations storage policy must preserve 8 GiB host-free and 4 GiB emergency thresholds")
    if storage.get("minimum_host_capacity_gib") < (
        storage["application_budget_gib"] + storage["minimum_host_free_gib"] + storage["critical_host_free_gib"]
    ):
        raise ValueError("minimum host capacity must fit the application budget and free-space reserves")
    if storage.get("buildkit_cache_gib") != 8 or storage.get("backup_total_max_gib") != 8:
        raise ValueError("storage policy lost its bounded BuildKit/backup retention limits")
    if storage.get("backup_file_max_gib") != 4:
        raise ValueError("one PCRStudio database backup must be capped at 4 GiB")
    if storage.get("ownership_roots") != ["application", "docker", "containerd"]:
        raise ValueError("operations storage policy must measure application, Docker and containerd roots")

    diagnostics = DIAGNOSTICS.read_text(encoding="utf-8")
    seen: set[str] = set()
    alerts = data.get("alert") or []
    if not alerts:
        raise ValueError("operations policy must define alerts")
    for alert in alerts:
        alert_id = str(alert.get("id") or "")
        if not re.fullmatch(r"PCRStudio[A-Za-z0-9]+", alert_id) or alert_id in seen:
            raise ValueError(f"invalid/duplicate alert id: {alert_id!r}")
        seen.add(alert_id)
        if alert.get("severity") not in {"warning", "critical"}:
            raise ValueError(f"{alert_id}: severity must be warning or critical")
        if not str(alert.get("expr") or "").strip() or not str(alert.get("for_duration") or "").strip():
            raise ValueError(f"{alert_id}: expr and for_duration are required")
        metrics = [str(item) for item in alert.get("metrics") or []]
        if not metrics:
            raise ValueError(f"{alert_id}: at least one metric is required")
        for metric in metrics:
            if metric not in diagnostics:
                raise ValueError(f"{alert_id}: metric is not emitted by diagnostics.rs: {metric}")


def runtime_payload(data: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": data["schema_version"],
        "release_line": data["release_line"],
        "generated_policy": "Generated from contracts/operations.toml; do not hand-edit.",
        "canonical_source": "contracts/operations.toml",
        "canonical_sha256": sha256(SOURCE),
        "backup": data["backup"],
        "storage": data["storage"],
        "alerts": data.get("alert") or [],
    }


def yaml_string(value: str) -> str:
    # JSON string syntax is a valid YAML double-quoted scalar and avoids a
    # dependency on a YAML serializer in the source-only release builder.
    return json.dumps(value, ensure_ascii=False)


def render_alerts(data: dict[str, Any]) -> str:
    lines = [
        "# @generated by scripts/generate-operations-policy.py from contracts/operations.toml; do not edit.",
        "groups:",
        "  - name: pcrstudio-current",
        "    rules:",
    ]
    for alert in data.get("alert") or []:
        lines.extend(
            [
                f"      - alert: {alert['id']}",
                f"        expr: {alert['expr']}",
                f"        for: {alert['for_duration']}",
                "        labels:",
                f"          severity: {alert['severity']}",
                "          service: pcrstudio",
                "        annotations:",
                f"          summary: {yaml_string(str(alert['summary']))}",
                f"          runbook: {yaml_string('docs/OPERATIONS.md#' + str(alert['runbook']))}",
            ]
        )
    return "\n".join(lines) + "\n"


def write_or_check(path: Path, content: str, *, check: bool) -> bool:
    if check:
        return path.is_file() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with SOURCE.open("rb") as handle:
        data = tomllib.load(handle)
    validate(data)
    runtime = json.dumps(runtime_payload(data), indent=2, ensure_ascii=False, sort_keys=True) + "\n"
    alerts = render_alerts(data)
    okay = write_or_check(RUNTIME, runtime, check=args.check)
    okay = write_or_check(ALERTS, alerts, check=args.check) and okay
    if args.check and not okay:
        raise SystemExit("generated operations policy is stale")
    print("OPERATIONS_POLICY=" + ("CURRENT" if args.check else "GENERATED"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
