#!/usr/bin/env python3
"""Turn the per-assay review into something a person can read.

The JSON beside it is the source. This file exists so the readable document can
be regenerated rather than edited: a hand-edited copy of a generated document is
two documents that disagree, and the disagreement is discovered by whoever
trusts the wrong one.

    python scripts/render-design-review.py
"""

from __future__ import annotations

import collections
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs/research/design-pages-per-assay.json"
OUT = ROOT / "docs/audits/design-pages-per-assay.md"


def main() -> None:
    doc = json.loads(SOURCE.read_text(encoding="utf-8"))
    base = doc["baseline"]
    modules = {m["id"]: m for m in base["modules"]}
    lines: list[str] = []
    w = lines.append

    w("# The twenty-one design pages, reviewed one assay at a time")
    w("")
    w(f"Generated from `{SOURCE.relative_to(ROOT).as_posix()}` by")
    w("`scripts/render-design-review.py`. Do not edit this file by hand —")
    w("regenerate it. The JSON is the source, and the build plan was written from it.")
    w("")
    w(f"Measured against commit `{doc['how']['measuredAgainstCommit'][:12]}`.")
    w("")

    w("## How this was made")
    w("")
    w(doc["how"]["method"])
    w("")
    w(f"{doc['how']['agents']} agents. {doc['how']['note']}")
    w("")

    counts = doc["counts"]
    w("## What it found")
    w("")
    w("| | |")
    w("| --- | ---: |")
    w(f"| Modules reviewed | {counts['modules']} |")
    for verdict, n in sorted(counts["verdicts"].items(), key=lambda x: -x[1]):
        w(f"| — verdict `{verdict}` | {n} |")
    w(f"| Questions an assay must ask | {counts['questions']} |")
    w(
        f"| …that no engine can currently take | **{counts['questionsTheEngineCannotTake']}** |"
    )
    w(f"| Things the current page gets wrong | {counts['thingsWrongToday']} |")
    w(f"| Steps that do not fit their assay | {counts['stepsThatDoNotFit']} |")
    w(f"| Tools an assay will want later | {counts['toolsWantedLater']} |")
    w("")

    w("## The page every module shares today")
    w("")
    w("`web/src/components/project/workspace.tsx` renders these five steps for all")
    w("twenty-one modules:")
    w("")
    for i, step in enumerate(base["sharedForm"]["steps"], 1):
        w(f"{i}. **{step['title']}** (`{step['id']}`)")
    w("")
    w("Step 2 offers the same fifteen numbers to every assay, whatever it is:")
    w("")
    w("| Field | Shown as | Default |")
    w("| --- | --- | ---: |")
    for field in base["sharedForm"]["constraintFields"]:
        w(f"| `{field['name']}` | {field['label']} | {field['default']} |")
    w("")

    w("`web/src/components/design/engine-fields.tsx` adds one card for eight of the")
    w(
        "eleven engines. Three get nothing at all: "
        + ", ".join(f"`{e}`" for e in base["engineCards"]["enginesWithNoCard"])
        + "."
    )
    w("")
    w("| Engine | Card | What it asks |")
    w("| --- | --- | --- |")
    for engine, card in sorted(base["engineCards"]["cards"].items()):
        w(f"| `{engine}` | {card['heading']} | {', '.join(card['asks']) or '—'} |")
    w("")

    w("## Which module runs which engine")
    w("")
    w("| Module | Engine | Goal | Card today |")
    w("| --- | --- | --- | --- |")
    for module in sorted(base["modules"], key=lambda m: (m["engine"], m["id"])):
        w(
            f"| `{module['id']}` | `{module['engine']}` | {module['goal']} | "
            f"{module['card'] or '**none**'} |"
        )
    w("")

    w("## Per module")
    w("")
    for mid in sorted(doc["perModule"]):
        entry = doc["perModule"][mid]
        checked = entry["checked"]
        meta = modules.get(mid, {})

        w(f"### {meta.get('name', mid)} — `{mid}`")
        w("")
        w(
            f"Engine `{meta.get('engine')}` · goal `{meta.get('goal')}` · "
            f"card today: {meta.get('card') or '**none**'}"
        )
        w("")
        w(f"**Verdict: `{checked.get('verdict')}`**")
        w("")

        if checked.get("mustAsk"):
            w("#### What it must ask, in order")
            w("")
            for i, ask in enumerate(checked["mustAsk"], 1):
                field = ask.get("engineField") or ""
                mark = (
                    " — ⚠️ **the engine cannot take this**"
                    if "MISSING" in field
                    else f" — `{field}`"
                )
                w(f"**{i}. {ask['question']}**{mark}")
                w("")
                w(f"{ask['why']}")
                w("")
                if ask.get("checked"):
                    w(f"*Checked against:* {ask['checked']}")
                    w("")

        for heading, key in (
            ("Wrong today", "wrongToday"),
            ("Steps that do not fit", "stepsThatDoNotFit"),
            ("Room to leave for later", "toolsLater"),
        ):
            if checked.get(key):
                w(f"#### {heading}")
                w("")
                for item in checked[key]:
                    w(f"- {item}")
                w("")

        removed = entry["removedByTheSceptic"]["questions"]
        if removed:
            w("#### Removed on checking")
            w("")
            w("The reviewer raised these; the sceptic could not confirm them against a")
            w("file. Kept, because a claim that sounds right and is not is worth")
            w("remembering the next time somebody has the same idea.")
            w("")
            for item in removed:
                w(f"- ~~{item}~~")
                w("")

        w("---")
        w("")

    w("## The build plan")
    w("")
    w(doc["buildPlan"] or "_(no plan returned)_")
    w("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    kinds = collections.Counter(
        "missing" if "MISSING" in (a.get("engineField") or "") else "present"
        for m in doc["perModule"].values()
        for a in m["checked"].get("mustAsk", [])
    )
    print(
        f"wrote {OUT.relative_to(ROOT).as_posix()} "
        f"({OUT.stat().st_size // 1024} KB, {len(lines)} lines)"
    )
    print(
        f"  questions: {sum(kinds.values())}, of which {kinds['missing']} need engine work"
    )


if __name__ == "__main__":
    main()
